# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FFMpeg-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FFMpeg-Example
#  pod "FFmpegNew-iOS"

  pod 'mobile-ffmpeg-full', '~> 4.3'


end
